//  @flow

export const errorCodes = {
  EMPTY_FIELDS: 'EMPTY_FIELDS',
  INVALID_EMAIL_PASSWORD: 'INVALID_EMAIL_PASSWORD',
  USER_EXISTS: 'USER_EXISTS',
  PASSWORD_CONFIRMATION_ERR: 'PASSWORD_CONFIRMATION_ERR',
};
